swagger:
  enable: true
  base-package: com.demo.service

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /swagger-ui.html

hystrix:
  command:
    config-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #默认为2000

config-server:
  ribbon:
    ConnectTimeout: 20000 #默认为1000
    ReadTimeout: 30000 #默认为1000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ignored-services: config-server,platform-sys,platform-tools
  ignored-patterns: /**/hello/**
  prefix: /api
  routes:
    config-server:
      path: /config/server/**
      serviceId: config-server
    platform-sys:
      path: /platform/sys/**
      serviceId: platform-sys
    platform-tools:
      path: /platform/tools/**
      serviceId: platform-tools
